### ISSUE TITLE
New Status page using the Rest API

### ISSUE THREAD

**Issue by deqw** [serkri/SmartEVSE-3#10]
Is the HTML for this new status page (like in the screenshot) provided by the firmware or is it just the JSON from the GET /settings API? If there is the complete HTML what is the correct URL? Thanks!

**Comment by k-janssens** [comment]
It is part of the firmware but you need to update your evse with the spiffs.bin file

**Comment by deqw** [comment]
Got it! Thanks.

**Comment by dingo35** [comment]
Can I flash the "original" spiffs.bin file thats in the firmware_V3.0.0_ORIGINAL.zip, or do I need to generate one? 

A ctrl-f5 in the vscode environment gives me a clean firmware.bin, but no new spiffs.bin ?
