### ISSUE TITLE
API mains with EV modbus

### ISSUE THREAD

**Issue by bartv** [serkri/SmartEVSE-3#118]
I am trying to configure it to work with an API based mains meter. I also have a modbus based meter for the EV. It seems that the EVSE never tries to read data over modbus. (The telephone on the meter does not show)

I deployed a debugging version of the hardware and I see no modbus setup message. Could it be that this setup is not supported? I am not 100% up to speed with the code base but this one seems to be the cause:

https://github.com/serkri/SmartEVSE-3/blob/master/SmartEVSE-3/src/evse.cpp#L2570

**Comment by dingo35** [comment]
#88 is the same issue, you can test the binary thats uploaded there. It will be merged in main branch in a few weeks...
