### ISSUE TITLE
Can't select OFF

### ISSUE THREAD

**Issue by martijndierckx** [serkri/SmartEVSE-3#136]
When clicking OFF, or when manually POSTing 'settings?mode=0', the evse stays in NORMAL/SOLAR/SMART.
I can change between the other modes. Rebooting doesn't work either

Any ideas?

v 1.6.2

**Comment by martijndierckx** [comment]
When I click OFF, the EVSE keeps showing NORMAL, but the charging does stop.
The LCD then immediatly starts displaying Ready To Charge and starts counting down. At which point the charging starts again.

And since EVCC.io sends an OFF command each second, this makes everything go into charge loop which cannot be healthy for the onboard charger.

**Comment by dingo35** [comment]
I can reproduce this, stay tuned.

**Comment by dingo35** [comment]
This is a strange phenomenon, I pulled v1.6.2, please go back to v1.6.1 for your production version. As soon as I understand whats going on I will release a fixed v1.6.3

**Comment by dingo35** [comment]
Fixed in https://github.com/serkri/SmartEVSE-3/releases/tag/v1.6.2.1
