### ISSUE TITLE
API 'connected' bool or string?

### ISSUE THREAD

**Issue by deqw** [serkri/SmartEVSE-3#14]
The Swagger API documentation shows a boolean as 'connected' value. The settings API however, returns a string like "false" and "true", which then is handled/compared in code as a string. Let's say that the Swagger solution is the better ;o). For good practice the API should return a bool value, but then the code must be reworked.

**Comment by koen-serneels** [comment]
Fair enough. Any other inconsistencies that you see? If not I'll prepare a release as it won't break much probably

**Comment by deqw** [comment]
Not at the moment, I will take another look tomorrow. No need to hurry to prepare a new binary since it’s working as it is now.

**Comment by koen-serneels** [comment]
Assume fixed
