### ISSUE TITLE
Version info in WEB page

### ISSUE THREAD

**Issue by Sonusss** [serkri/SmartEVSE-3#141]
Building the latest version show building date and time as version information instead of version number.
Same in Raw Data :  version | "14:37:23 @May  9 2023"

![Screenshot from 2023-05-09 15-41-59](https://github.com/serkri/SmartEVSE-3/assets/51654027/4f4d0409-9c7c-40f7-9092-5bdeacf7b4c2)

**Comment by dingo35** [comment]
That is intentional, so we can see whether you use an official build or a self compiled version.
