### ISSUE TITLE
Delayed charging for solar mode

### ISSUE THREAD

**Issue by hmmbob** [serkri/SmartEVSE-3#147]
The docs read the following:

> the SmartEVSE will stay on indefinitely. Delayed Charging in Solar mode is not supported, since in Solar mode the sun will decide when charging starts...

I would still like to use delayed start for solar mode 😄  The reason is financial: I have plenty of PV panels and am on a dynamic contract (hourly prices). Because of the dynamic prices, it is sometimes more favorable for me to wait to use my own energy until the prices are extremely low, because then returning to grid is completely not interesting. Like yesterday, "use yourself" is very interesting from 12h on, whilst returning to grid was more beneficial in the hours before that, so I would have loved to delay solar charging until after 12:00:

![image](https://github.com/serkri/SmartEVSE-3/assets/33529490/41bc89bf-7529-45f9-97bb-1ab83488663c)

Another use case is that one might want to wait until solar production is higher, because charging with a higher rate leads to less losses in the systems (it is more efficient to charge with 11kW instead of 3.2kW).

Is there a possibility to also add "delayed start" in solar mode?

**Comment by dingo35** [comment]
Have some patience my friend!

**Comment by mr-leo** [comment]
When you have a dynamic contract and the price is low, it makes more sense to charge as fast as you can (normal/smart mode) instead of solar mode and also take energy from the grid, doesn't it? So that you can make more use of the low prices.

**Comment by hmmbob** [comment]
"Low price" vs "paying nothing at all because I am using my own solar production"

option 2 is better 😉

**Comment by mr-leo** [comment]
No because you get the exact same amount as you pay with dynamic prices. So you pay 6ct of get 6ct..

**Comment by hmmbob** [comment]
I know how dynamic pricing works - I don't see why this discussion is relevant for the request?

**Comment by dingo35** [comment]
IMHO any discussion on the use case is relevant, to prevent function creep.....

**Comment by dingo35** [comment]
But how does it look if you do Smart charging with delay until 12:00 ?

**Comment by hmmbob** [comment]
> But how does it look if you do Smart charging with delay until 12:00 ?

Gimme a sec.

**Comment by dingo35** [comment]
And so we all learn a bit; thanks for your work! 
I still have enabling delayed solar charging on my list, because I believe in maximum user freedom as long as it doesn't ask for to much code. In fact it might even reduce some code :-) . But I always like to understand my users cases..... and you are right, if dynamic pricing stops paying the same amount as charging, it will be a different ball game.

**Comment by mr-leo** [comment]
If you already use HA, you can set the mode from OFF to SOLAR at the desired time, and don't need the timer on the SmartEVSE at all. You can even automate it at the cheapest moment.

**Comment by deqw** [comment]
> If you already use HA, you can set the mode from OFF to SOLAR at the desired time, and don't need the timer on the SmartEVSE at all. You can even automate it at the cheapest moment.

I did so and used Node Red to make some charge policies. I’m not sure but when I use Solar mode it looks to me that the SmartEVSE tries to prevent using power from the net, to a certain level. 
![IMG_7023](https://github.com/serkri/SmartEVSE-3/assets/65849349/761bde4d-f56c-46c3-a23f-d06a98bef3b4)

**Comment by hmmbob** [comment]
> > If you already use HA, you can set the mode from OFF to SOLAR at the desired time, and don't need the timer on the SmartEVSE at all. You can even automate it at the cheapest moment.
> 
> I did so and used Node Red to make some charge policies. I’m not sure but when I use Solar mode it looks to me that the SmartEVSE tries to prevent using power from the net, to a certain level. ![IMG_7023](https://user-images.githubusercontent.com/65849349/239980785-761bde4d-f56c-46c3-a23f-d06a98bef3b4.png)

Nice! Got your code avail somewhere?

**Comment by deqw** [comment]
Not right now, but no problem to share. I will document it and share it here if that is possible.

**Comment by deqw** [comment]
@hmmbob That involves a lot of screenshots and additional work for you. Just install Node-Red on HA and import the json and you will be on your way in a few minutes. Besides that, I'm using Safari on MacOS which has a bug with forms resulting in not showing all the forms properties, so a lot of screenshots will have incomplete information (empty properties).

Let me know what you are going to do?

Anyway, this is the complete flow:

![Screenshot 2023-05-25 at 15 09 18](https://github.com/serkri/SmartEVSE-3/assets/65849349/116e5cc2-b4af-46c0-918f-ae47a58a6465)
