### ISSUE TITLE
Charging L2 L3 reporting false - 1.6.5

### ISSUE THREAD

**Issue by deqw** [serkri/SmartEVSE-3#151]
While 3 phase charging (1.6.5)  the sensors Charging L2 and Charging L2 are reporting false and Charge in the web GUI reports 1 x 13.0 A. Attached some screenshots of the situation. Is this correct?

 
![Screenshot 2023-05-28 at 14 19 55](https://github.com/serkri/SmartEVSE-3/assets/65849349/eb980626-cb27-467b-86ea-a1a1093dfdf1)
![Screenshot 2023-05-28 at 14 21 28](https://github.com/serkri/SmartEVSE-3/assets/65849349/b0703574-09c5-49ec-b7ef-b983f87f3ce2)
![Screenshot 2023-05-28 at 14 22 16](https://github.com/serkri/SmartEVSE-3/assets/65849349/6c7c3185-f9d2-403b-839a-db1382aa24f9)

**Comment by dingo35** [comment]
Is your car a Tesla by coincidence?

**Comment by deqw** [comment]
No it's a BMW iX3.

**Comment by dingo35** [comment]
Perhaps you can post a verbose telnet log? 
It could be a bug, but similar behaviour happened with a Tesla that started drawing current on a single phase and only after 11-25 seconds it started charging over the other phases...

**Comment by deqw** [comment]
But at the moment of the screenshots it was already charging 3 phase for 21 minutes and drawing current on L1 L2 L3 from the start/1st second.

**Comment by deqw** [comment]
I noticed this morning that without charging and with or without the cable connected to the car:

![Screenshot 2023-05-29 at 12 32 25](https://github.com/serkri/SmartEVSE-3/assets/65849349/7877c1f1-34ac-4629-bb48-41d00fda833f)

Then I did a reboot via the web interface (no cable connected) and it changed to:

![Screenshot 2023-05-29 at 12 34 15](https://github.com/serkri/SmartEVSE-3/assets/65849349/a5540840-a375-4580-a991-c894c0dc6d46)

![Screenshot 2023-05-29 at 12 34 43](https://github.com/serkri/SmartEVSE-3/assets/65849349/a2c84a67-2d4a-4214-8048-3d7bce891402)

Is this the correct reporting for L1, L2 and L3 in this situation?

**Comment by dingo35** [comment]
Those booleans only have meaning during a charging session.

**Comment by dingo35** [comment]
Committed in 14abe7cb0bf4
