### ISSUE TITLE
Remove hard-coded battery capacity from modem logic

### ISSUE THREAD

**Issue by ArendJanKramer** [serkri/SmartEVSE-3#155]
Currently the modem code is hard-coded to 28kWh.

Todo:

- Adjust callback endpoint of SmartEVSE, to accept battery capacity as input
- Adjust pyPLC, so extract battery information from modem

Please assign to myself

**Comment by arpiecodes** [comment]
https://github.com/serkri/SmartEVSE-3/pull/160 should solve this issue ✅ 

Of course feedback always welcome! Especially on my creative MODEM_DENIED state.
