### ISSUE TITLE
Posible wrong information in Homeassistant

### ISSUE THREAD

**Issue by HansNetcom** [serkri/SmartEVSE-3#156]
Hi,
Thnx for the great development of the smart EVSE.
I,m using is frequently to charge my car on sun-power only :-)

I,m experimenting with the HA integration and noticed a possible error in displaying information.
Although the smartEVSE is OFF and there is no car connected, home-assitant reports smartcharching on L1 TRUE. L2 and L3 reports false.

![screenshot HA smartEVSE](https://github.com/serkri/SmartEVSE-3/assets/52430442/9420e203-f762-4055-b370-b368665c3808)

**Comment by dingo35** [comment]
That is debug info that gives you info on your last charging session; not useful to display.

**Comment by HansNetcom** [comment]
OK, thank you for the swift response
