### ISSUE TITLE
Settings page increase precision from 1 to 3 decimals

### ISSUE THREAD

**Issue by evanes68** [serkri/SmartEVSE-3#161]
I have a home automation platform that reads data from the smartevse settings page.
For example the charged_kwh field provides data to see how the charge is progressing. 

Currently the data has one decimal precision meaning that it takes a while before you see any data.
I would prefer to see three decimal precision having a much more responsive indication of the charging process.

For example I would change line:
  doc["ev_meter"]["charged_kwh"] = round(EnergyCharged / 100)/10; //in kWh, precision 1 decimal
To:
  doc["ev_meter"]["charged_kwh"] = round(EnergyCharged)/1000; //in kWh, precision 3 decimal

This can best be done for all fields that have this calculation for mains_meter and ev_meter.

**Comment by dingo35** [comment]
If you want precise progress information you should watch the currents, because that gives you the _actual_ charge at that moment.
A more precise indication will only clobber up your database; feel free to adapt the code to your needs, I dont think mainstream users are interested in this.
