### ISSUE TITLE
New 2023 Range Rover Sport Hybrid problems disconnecting charge cable

### ISSUE THREAD

**Issue by evanes68** [serkri/SmartEVSE-3#162]
I do not know if this is an issue with the car or SmartEVSE.

When I had this car for a test drive I was wondering at what speed it would charge. I connected the cable to the car and charging started just as it always does on my BMW. After 10 minutes I wanted to stop the charge and drive the car. Strangely enough I could not get the cable to release from the car.

The Range Rover Sport has an unlock button next to the cable. The charge indicator changes from green to white but the locking mechanism was not unlocked. I tried disabling the SmartEVSE but the car just showed a message on the dashboard "Initializing".

After contacting the dealer we tried all sorts of procedures. When the car was locked again it would restart charging but every attempt at stopping the charge would signal "Initializing" and a locked cable...

In the end we found there was an emergency release cable in the luggage department behind a small door. This finally released the cable.

Because it was a test drive I cannot check the car again. I Hope it was a car issue, the dealer said they charged the car daily with another charger without issue. So maybe SmartEVSE does not work with Range Rover?

Any one else have this issue?

**Comment by dingo35** [comment]
The EV is in control of releasing the cable, it has nothing to do with the SmartEVSE.

That can only control an actuator, if installed, for locking a non-fixed cable to the charger socket (so not the EV socket).
