### ISSUE TITLE
Car connected wrong sensor value

### ISSUE THREAD

**Issue by negronoir** [serkri/SmartEVSE-3#165]
Hello,

In v1.6.7 the 'sensor.smartevse_car_connected' doesn't show if car is connected. Always takes the opposite value of 'sensor.smartevse_access' despite if car is connected or not.

If I set 'true' the access, the car connected sensor changes to 'false'

If I set 'false' the access, the car connected sensor changes to 'true'

In former versions including v1.6.6, this works fine. 

Thanks

**Comment by dingo35** [comment]
Thanks for your bug report; this version should solve the problem, could you please test?
[nomodem.zip](https://github.com/serkri/SmartEVSE-3/files/11990383/nomodem.zip)

**Comment by dingo35** [comment]
Fixed in v1.7.0.

**Comment by negronoir** [comment]
Hi!

Sorry for the delay in the answer. I was on holidays out of home.

Checked and fixed.

Thanks!!
