### ISSUE TITLE
Some MQTT setting fields are empty after page reload

### ISSUE THREAD

**Issue by hmmbob** [serkri/SmartEVSE-3#166]
I've succesfully connected the SmartEVSE to my mqtt server (great!), but when I now reopen the mqtt settings tab some fields are empty:

![image](https://github.com/serkri/SmartEVSE-3/assets/33529490/ad1aa41d-5d86-4379-9bdf-f30a282b33ab)

I expected to see the current config here (maybe without the password or so).

**Comment by hmmbob** [comment]
Is there any way to connect to the SmartEVSE and edit the index.html directly, or is there always a new build needed?

I have no experience with the latter (I always update with your provided binaries), so I haven't tested this locally. However, given that the key names were just not matching, I'm 99% sure this is fixed with the PR submitted.

**Comment by dingo35** [comment]
You can test your local index.html easy by editing the line that has 10.0.0.36 in it; comment the line above it, change it to your own smartevse's ip address, and if you approach file:///path to your local index.html you can see immmediate results

**Comment by hmmbob** [comment]
The "local override" (see edit above) worked - it's confirmed tested

**Comment by dingo35** [comment]
Yup we were typing in parallel; hope to test this afternoon.

**Comment by dingo35** [comment]
@hmmbob Thanks for your work!

**Comment by deekoowee** [comment]
@hmmbob , how did you reach the mqtt config page ?
![image](https://github.com/serkri/SmartEVSE-3/assets/121685906/e2febeb6-17c5-4efe-a2b7-046628378f65)
My Smart EVSE main page looks like this;
![image2](https://github.com/serkri/SmartEVSE-3/assets/121685906/4c626648-a08c-4ab4-9a6e-4b4359482a94)

**Comment by hmmbob** [comment]
Did you flash spiffs too? Or only firmware.bin?

**Comment by deekoowee** [comment]
I have flashed only firmware.bin
Now I flashed spiffs too and config functionality appears on main screen.
Thanks for helping on this.
