### ISSUE TITLE
Control via IoBroker using API

### ISSUE THREAD

**Issue by Elektrofix-OL** [serkri/SmartEVSE-3#183]
I am trying to control the SmartEVSE with the IoBroker. Since the SunnyHomemanger is not directly supported, I would like to send the data from the eHZ to the EVSE. I'm trying a url call 
http://192.168.5.23/currents?L1=15&L2=-10&L3=-11
but the EVSE shows nothing in the browser.
In the EVSE I set the MainMeter to API. Firmware SERKRI-1.7.1

What am I doing wrong?

**Comment by dingo35** [comment]
You should send values in Amps x 10; so if you want to send 1.5A you should send 15.

You could try using curl, like: curl -X POST http://etc. , if that works than your system is either sending a GET or not the right syntax...

Also note you should send the info every few seonds, and it takes the webserver UI 6secs to refresh

**Comment by Elektrofix-OL** [comment]
I got it. It is important that it is not a „request“ but an „exec“ as curl with ' character, otherwise nothing arrives.
Here is my Blockly:
![IMG_0598](https://github.com/serkri/SmartEVSE-3/assets/39242936/c27da2d8-1b53-4f31-b53e-075c071ed6ae)
