### ISSUE TITLE
Integration of SMA meters into the SmartEVSE

### ISSUE THREAD

**Issue by Elektrofix-OL** [serkri/SmartEVSE-3#186]
Is it possible to integrate the SMA-EM counters into the program?
The meters from SMA and also the HomeManager 2 send a multicast to 239.12.255.254:9522 every 200ms with all important information.
I found the adapter for the IoBroker on Github, which reads the data out of the network.
https://github.com/iobroker-community-adapters/ioBroker.sma-em 
Unfortunately my programming skills stop at Turbo Pascal 20 years ago and the google translator is my friend.

**Comment by dingo35** [comment]
I would recommend to do this via HomeAssistant, which interfaces to Iobroker (https://github.com/ioBroker/ioBroker.hass).
