### ISSUE TITLE
Modbus Server off ??

### ISSUE THREAD

**Issue by rvdgaag** [serkri/SmartEVSE-3#201]
Since update to 1.7.3 I can't pull any data via modbus, before it worked flowlessly

Any idea?

**Comment by dingo35** [comment]
A bit unclear if you are using MQTT and/or REST API, but this might be the problem:
https://github.com/serkri/SmartEVSE-3/issues/196

**Comment by rvdgaag** [comment]
sorry, can close the issue. I added an extra modbus meter in the chain for the second smartevse and it was set to the wrong baudrate which disturbed the modbus pulls.

I'm using both MQTT, pushing the mains meter data via API and reading the EV meters via the SMARTEVSE modbus server.
