### ISSUE TITLE
Feature request: stop charging at xx% full

### ISSUE THREAD

**Issue by the-master006** [serkri/SmartEVSE-3#207]
Since apparently it is beneficial for the car battery to only charge it to max ~80%, would be a very nice feature if this is possible. I don't know what kind of communication goes over the single wire, but if percentage charged can be read, than this should be possible.
Thanks for your feedback!

**Comment by dingo35** [comment]
SoC cannot be read without special hardware.
A workaround is to find an integration for your EV and steer your SmartEVSE from there.
The simple way is to have your EV handle this.
