### ISSUE TITLE
PLC modem support: how?

### ISSUE THREAD

**Issue by JeroenVanOort** [serkri/SmartEVSE-3#208]
I know there are some people tinkering with Power Line Communication (PLC) modems to communicate with cars about the SoC and what not. There is some support in the code. But how can I make this work for me? Is there any documentation on this? Some place where I can read up on development?

**Comment by dingo35** [comment]
Here is where the experts convene:
https://github.com/SmartEVSE/SmartEVSE-3/issues/25
