### ISSUE TITLE
Screen goes flickering black

### ISSUE THREAD

**Issue by Imaginous** [serkri/SmartEVSE-3#234]
During charging the screen goes black with some flickering pixels after about 2 hours of charging.

Often after stopping charging the screen returns to normal after a minute or so.

Is this a software issue or a hardware failure? 
![PXL_20240112_203726023](https://github.com/serkri/SmartEVSE-3/assets/68418842/45ef4dda-6fd3-4fa6-9848-f3952ebb8574)

**Comment by dingo35** [comment]
Looks like a hardware issue; flash latest release to see if its solved!

**Comment by Imaginous** [comment]
It didn't help, I contacted the supplier.
