### ISSUE TITLE
switching normal/off modes via API in master-slave configuration.

### ISSUE THREAD

**Issue by jaroslawp** [serkri/SmartEVSE-3#25]
When I change modes between solar and smart (or other way around) on the master smartevse via API call it works as expected for the slave too. However when I switch mode to normal: both master and slave change but while switching back to solar or smart - master changes but slave stays on solar. When switching to off mode from solar/smart: master switches but state of slave is unchanged.

I know I can switch the mode separately on slave via its API endpoint: but apparently this disturbs bus communication between master and slave and as a result slave never starts charging after .. until both master and slave are power-cycled this is not recovering.

**Comment by koen-serneels** [comment]
As I'm not using a slave myself, can you first try if this issue also exists in the original firmware?
