### ISSUE TITLE
POST settings not working

### ISSUE THREAD

**Issue by martijndierckx** [serkri/SmartEVSE-3#26]
GET on /settings works
But a POST on /settings doesn't provide a response?

Excerpt from postman:
``` 
curl --location --request POST 'http://192.168.8.4/settings?override_current=60' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```

Any ideas?

**Comment by k-janssens** [comment]
The system will only allow to override the current when the mode is set to NORMAL.
So my first guess would be the current mode is not NORMAL
