### ISSUE TITLE
3 Phase wire scheme

### ISSUE THREAD

**Issue by martijndierckx** [serkri/SmartEVSE-3#31]
Can you confirm wiring for 2 contactors in order to switch between 1P and 3P charging should be like this?
(If so, can you update the manual as well?)

![](https://user-images.githubusercontent.com/3973630/176630385-3720ae35-6931-4d89-a9ce-f8802da9da4b.png)

Linked issue: #18

**Comment by k-janssens** [comment]
That is correct, it felt for us to be the safest setup. 
For example: with 2x 2P in parallel you could have 2 live fase wires without the neutral if for some reason the contactors aren't working/controlled correctly.

**Comment by koen-serneels** [comment]
Below a complete setup when already having an existing installation and the EVSE is placed in a  new cabinet. Of course, many variations are possible depending on local regulations. This setup at least was approved in Belgium. The type B diffs are important as a 6mA DC leak current protection must be in place. Note that when having a type B diff it not allowed/not safe to have upstream type A diffs.

Disclaimer: use at your own risk!

![evse](https://user-images.githubusercontent.com/1129913/177944008-e2a2e494-4dba-42a4-8154-3391171a7c03.png)
