### ISSUE TITLE
Request info in interface

### ISSUE THREAD

**Issue by rvdgaag** [serkri/SmartEVSE-3#34]
The EVSE is showing the total of the charged kWh's from the EV Eastron modbus unit.

Really would like to have this info displayed in the web interface too.

Thanks for the great work!

**Comment by dingo35** [comment]
Sure but I'm a bit busy for the next few weeks, do if there is no hurry you can put it on my list.

**Comment by fluppie** [comment]
I added this a while ago in evse.cpp around line 2969-2970

```
        doc["ev_meter"]["EVMeter"] = EMConfig[EVMeter].Desc;
        doc["ev_meter"]["EVMeter_addr"] = EVMeterAddress;
        doc["ev_meter"]["EVMeter_total_kWh"] = EnergyEV;
        doc["ev_meter"]["EVMeter_charged_kWh"] = EnergyCharged;
        doc["ev_meter"]["EVMeter_W"] = PowerMeasured;
```

**Comment by k-janssens** [comment]
I updated the API and index page, it should include now the EV meter data (if enabled).
It's in release v1.3.8-serkri-v3

**Comment by fluppie** [comment]
Real value is 3148,492 kWh, only have the car for 6 months not 500 years :)
![afbeelding](https://user-images.githubusercontent.com/8402106/180621257-ff719119-b626-417b-87ec-06b730f65973.png)

**Comment by k-janssens** [comment]
I don't have a kwh meter connected with my evse so I'm not able to test, what should the value be?

**Comment by rvdgaag** [comment]
Same issue here, also Charged kWh is factor 1000 to high

**Comment by k-janssens** [comment]
Ah ok, the measurement is in Wh and not kWh

**Comment by fluppie** [comment]
Same for the Charged kWh :-)
But the power reading is broken, because the 1Phase Eastron meters have a different register, 0x0C vs 0x34 on the 3Phase variants. I fixed that in my own version, but I used your binaries now and that's why it's broken now.

![afbeelding](https://user-images.githubusercontent.com/8402106/180622126-ca8e650c-d44e-4fb9-9f2d-98c5d29435c2.png)

    {"1PEastron", ENDIANESS_HBF_HWF, 4, MB_DATATYPE_FLOAT32,    0x0, 0,    0x6, 0,   0x0C, 0,  0x156, 0}, // 1P Eastron SDM230 (V / A / W / kWh) max read count 80
    {"3PEastron", ENDIANESS_HBF_HWF, 4, MB_DATATYPE_FLOAT32,    0x0, 0,    0x6, 0,   0x34, 0,  0x156, 0}, // 3P Eastron SDM630 (V / A / W / kWh) max read count 80

**Comment by dingo35** [comment]
Suggest we report in kWh, with accuracy of 1 decimal, like all the other kWh values, to prevent unnecessary space occupation of long term storage databases, if any are used.

**Comment by k-janssens** [comment]
I made some time today to finally move myself to the 1.4 release branch. 
My changes with the kWh calculation will be soon in the 1.4 release once we merge it with the master.

**Comment by dingo35** [comment]
Great, welcome to the future :-)  !!!
