### ISSUE TITLE
Unlocking the cable

### ISSUE THREAD

**Issue by deqw** [serkri/SmartEVSE-3#43]
Is it possible to unlock the (fixed) cable at the car’s side from the SmartEVSE? Would like to have it unlocked with the switch or even not having it locked at all when charging starts with my inside SmartEVSE.

**Comment by k-janssens** [comment]
No, it is the car who does the locking at his end.

There are ways to (permanently) disable the locking capability by making slits in the charger cable where the locking holes are but I would not advise to do so. Also if you unlock the car, this mechanism should also unlock which is the preferred way.

**Comment by dingo35** [comment]
AFAIK it's the car that decides to unlock the cars side of the cable; SmartEVSE decides whether to unlock the socket side (if not fixed cable).

I solved this problem by defining a "home charge location", where I can specify "always unlock" (VAG ID-4 platform).

**Comment by deqw** [comment]
Thanks both for the swift reply. Will look if a “home charge location” option is available for my car.
