### ISSUE TITLE
Which version to use

### ISSUE THREAD

**Issue by deqw** [serkri/SmartEVSE-3#50]
I'm still using Version: SERKRI-1.4.0 and saw 1.3.8 published yesterday. When will these versions come together and what version to use for now? Does 1.3.8 include the WiFi solutions?

**Comment by k-janssens** [comment]
1.4 will be merged with the master in time.
1.3 is the one I initially released and still using until I find some time to test 1.4 properly on my own system.

Those changes of the past days are minor items I quickly needed that will be merged with 1.4 as wel

**Comment by deqw** [comment]
Thanks. I'm doing fine with 1.4.
