### ISSUE TITLE
Kostal KSEM Integration

### ISSUE THREAD

**Issue by Schnitzn** [serkri/SmartEVSE-3#70]
After successful installation of the SmartEvse with firmware upgrade to Serkri (thanks a lot for the extended functionality) I still fail to get the Modbus communication working out --> Error on Serial Communication

Installation was made with direct Modbus connection from the Smart Energy Meter (without Sensorbox). I am wondering if that is caused because in KSEM I can only select 9600 bps 8N2 (not 9600 8N1).
 
Would it be possible to integrate Kostal Smart Energy Meter (KSEM) Settings into the SmartEvse?

![SmartEvse NoCom](https://user-images.githubusercontent.com/115066621/194120101-71fa6444-63b5-4c8b-9c91-101260455db2.PNG)
![KSEM Modbus Settings](https://user-images.githubusercontent.com/115066621/194120114-9f8bad3e-c4b6-4d69-b85d-c7171e09b5b5.PNG)
https://www.kostal-solar-electric.com/de-de/produkte/zubehoer/smart-energy-meter/-/media/document-library-folder---kse/2020/12/15/13/54/ba_kostal_interface_ksem_en.pdf

**Comment by dingo35** [comment]
It is a very strange, non-standard decision of the manufacturer to demand 2 stopbits when no parity bits are configured.
The SmartEVSE is all standardized on 8N1 modbus usage, as are most modbus devices. We will not modify this standard.

If you want you could adapt the firmware yourself, but we would not recommend it.
