### ISSUE TITLE
RemoteDebug

### ISSUE THREAD

**Issue by hunter-nl** [serkri/SmartEVSE-3#76]
When  building a debug version and try to debug over WiFi with telnet. The telnet command responds immediately with ``` Connection refused ```
How can I do the remote debug?

**Comment by dingo35** [comment]
Edit include/evse.h:
1. comment the #define DEBUG_DISABLED 1 line
2. Change 
#define LOG_EVSE LOG_INFO                                                       
and/or
#define LOG_MODBUS LOG_WARN 

to LOG_DEBUG (or any info level you want)
3. Recompile & reflash

....and then a telnet server should be present at the default telnet port.

**Comment by hunter-nl** [comment]
Thanks. It’s working now.
