### ISSUE TITLE
using API for current POST every 10 seconds needed? 

### ISSUE THREAD

**Issue by johnvanl** [serkri/SmartEVSE-3#78]
I am using Smart EVSE V3 Version: SERKRI-1.4.4 in combi with Home Assistant.
And in stead of the p1-cable I am using the API with POST/currents.

In my configuration:
  laadpaal_share_p1:    url: http://<ip-address>/currents?L1={{ states('sensor.current_phase_l1')|float*10  }}&L2={{states('sensor.current_phase_l2')|float*10  }}&L3={{  states('sensor.current_phase_l3')|float*10  }}
    method: POST
In my automation:
 action:   
service: rest_command.laadpaal_share_p1
 
This works fine.
But I have learned that I have to POST at least every 10 seconds otherwise I will get an "Error: Communication Error" which will be solved with one (or some) new POST(s). My intention was to POST only when the current changes and the smart EVSE is <> OFF. I can understand that the Smart EVSE wants an update regularly. Is this 10 seconds maximum (and always needed even when it is OFF) or is there an option to optimize and mimimize the number of POSTs?

**Comment by dingo35** [comment]
That change is implementing a safety feature: if you cannot provide accurate current information every 10 seconds, SmartEVSE cannot do what it promises (guard currents in Smart mode, dynamic charging in Solar mode).

Homeassistant is ideal to read/write non-timecritical data, but (AFAIK) not meant for these kinds of update intervals. So better have some script load your P1 data directly into SmartEVSE (it monitors every 100ms), and from there load it into Homeassistant ....
