### ISSUE TITLE
Charge currents aren't adjusted to protect mains [Smart mode v1.5.0 with API current update]

### ISSUE THREAD

**Issue by age-creator** [serkri/SmartEVSE-3#98]
In Smart mode on version 1.5.0 the charge currents are sometimes not adjusted to keep the mains within limits, it continues to charge on maximum charge levels. After reboot the behaviour is back to normal. I'm using a 1 phase connection and updating the currents via the API.

**Comment by dingo35** [comment]
-upgrade to 1.5.2
-post the debug logs here that show that behaviour, so we can see what's going on....

**Comment by age-creator** [comment]
Upgraded to 1.5.2 and this solved the problem.
